use super::AppService;
use crate::{
    domain::{claim::Claim, expense::currency_exponent, id, now},
    error::{AppError, Result},
    repository::{self, claim_repository as claims, expense_repository as expenses},
};
use serde::{Deserialize, Serialize};
use std::{
    collections::{HashMap, HashSet},
    fs,
    io::Write,
};
use ts_rs::TS;
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CsvExport {
    pub id: String,
    pub file_name: String,
    pub path: String,
    pub rows: u32,
}
const HEADER: [&str; 13] = [
    "Claim Number",
    "Claim Title",
    "Receipt Ref",
    "Date",
    "Merchant",
    "Category",
    "Description",
    "Currency",
    "Amount",
    "Tax",
    "Status",
    "Receipt File",
    "Expense ID",
];
struct CsvRow {
    claim_number: String,
    claim_title: String,
    receipt_ref: String,
    date: String,
    merchant: String,
    category: String,
    description: String,
    currency: String,
    amount_minor: Option<i64>,
    tax_minor: Option<i64>,
    status: String,
    receipt_file: String,
    expense_id: String,
}
/// Prefixes a cell with `'` when it starts with a character a spreadsheet would
/// treat as the start of a formula, per the CSV export's formula-injection guard.
fn guard_formula(value: &str) -> String {
    if value.starts_with(['=', '+', '-', '@', '\t', '\r']) {
        format!("'{value}")
    } else {
        value.to_string()
    }
}
/// Quotes a field per RFC 4180 when it contains a comma, quote, or newline,
/// doubling any embedded quotes.
fn quote(value: &str) -> String {
    if value.contains([',', '"', '\n', '\r']) {
        format!("\"{}\"", value.replace('"', "\"\""))
    } else {
        value.to_string()
    }
}
/// A text cell: formula-guarded, then RFC 4180 quoted.
fn text_cell(value: &str) -> String {
    quote(&guard_formula(value))
}
/// Formats minor units as a plain decimal using integer arithmetic only, per
/// the currency's exponent (e.g. JPY -> "150", BHD -> "12.345").
fn format_money(minor: i64, exponent: u32) -> String {
    if exponent == 0 {
        return minor.to_string();
    }
    let factor = 10_i64.pow(exponent);
    format!(
        "{}.{:0width$}",
        minor / factor,
        minor % factor,
        width = exponent as usize
    )
}
/// The Amount/Tax cells are numeric values generated by the app, so they are
/// never formula-guarded or quoted (Global Constraints CSV rules).
fn money_cell(minor: Option<i64>, currency: &str) -> String {
    match minor {
        None => String::new(),
        Some(m) => format_money(m, currency_exponent(currency).unwrap_or(2)),
    }
}
/// The maximum number of collision-avoidance attempts tried against the
/// export directory: the base name, then ` (2)` through ` (999)`.
const MAX_EXPORT_COLLISION_ATTEMPTS: u32 = 999;
/// Builds the `n`th candidate file name for the export directory: `n == 1`
/// is the base human file name, `n >= 2` inserts ` (n)` before `.csv`.
fn export_candidate_name(file_name: &str, n: u32) -> String {
    if n <= 1 {
        return file_name.to_string();
    }
    match file_name.strip_suffix(".csv") {
        Some(stem) => format!("{stem} ({n}).csv"),
        None => format!("{file_name} ({n})"),
    }
}
fn render(rows: &[CsvRow]) -> Vec<u8> {
    let mut out = vec![0xEF, 0xBB, 0xBF];
    let header = HEADER
        .iter()
        .map(|h| text_cell(h))
        .collect::<Vec<_>>()
        .join(",");
    out.extend_from_slice(header.as_bytes());
    out.extend_from_slice(b"\r\n");
    for r in rows {
        let cells = [
            text_cell(&r.claim_number),
            text_cell(&r.claim_title),
            text_cell(&r.receipt_ref),
            text_cell(&r.date),
            text_cell(&r.merchant),
            text_cell(&r.category),
            text_cell(&r.description),
            text_cell(&r.currency),
            money_cell(r.amount_minor, &r.currency),
            money_cell(r.tax_minor, &r.currency),
            text_cell(&r.status),
            text_cell(&r.receipt_file),
            text_cell(&r.expense_id),
        ];
        out.extend_from_slice(cells.join(",").as_bytes());
        out.extend_from_slice(b"\r\n");
    }
    out
}
impl AppService {
    pub fn export_claim_csv(&self, claim_id: &str) -> Result<CsvExport> {
        let db = self.conn()?;
        let claim = claims::get(&db, claim_id)?;
        let members: Vec<_> = expenses::all(&db)?
            .into_iter()
            .filter(|e| e.claim_id.as_deref() == Some(claim_id))
            .collect();
        drop(db);
        let rows: Vec<CsvRow> = members
            .iter()
            .enumerate()
            .map(|(index, e)| CsvRow {
                claim_number: claim.claim_number.clone(),
                claim_title: claim.title.clone(),
                receipt_ref: e
                    .receipt_id
                    .as_ref()
                    .map(|_| format!("R{:03}", index + 1))
                    .unwrap_or_default(),
                date: e.occurred_at.clone().unwrap_or_default(),
                merchant: e.merchant_name.clone().unwrap_or_default(),
                category: e.category.clone(),
                description: e.description.clone(),
                currency: e.currency.clone().unwrap_or_else(|| claim.currency.clone()),
                amount_minor: e.total_amount_minor,
                tax_minor: e.tax_amount_minor,
                status: e.status.as_str().to_string(),
                receipt_file: e.receipt_filename.clone().unwrap_or_default(),
                expense_id: e.id.clone(),
            })
            .collect();
        let file_name = format!("Folio-{}.csv", claim.claim_number);
        self.write_csv_export(&rows, file_name, Some(claim_id))
    }
    pub fn export_expenses_csv(&self, expense_ids: Vec<String>) -> Result<CsvExport> {
        if expense_ids.is_empty() || expense_ids.len() > 5000 {
            return Err(AppError::invalid("Select 1 to 5000 expenses to export."));
        }
        let mut seen = HashSet::new();
        let mut unique = Vec::with_capacity(expense_ids.len());
        for raw in &expense_ids {
            uuid::Uuid::parse_str(raw).map_err(|_| AppError::invalid("Invalid expense ID."))?;
            if seen.insert(raw.clone()) {
                unique.push(raw.clone());
            }
        }
        let db = self.conn()?;
        let mut claim_cache: HashMap<String, Claim> = HashMap::new();
        let mut rows = Vec::with_capacity(unique.len());
        for eid in &unique {
            let e = expenses::get(&db, eid)?;
            let (claim_number, claim_title) = match e.claim_id {
                Some(ref cid) => {
                    if !claim_cache.contains_key(cid) {
                        let c = claims::get(&db, cid)?;
                        claim_cache.insert(cid.clone(), c);
                    }
                    let c = &claim_cache[cid];
                    (c.claim_number.clone(), c.title.clone())
                }
                None => (String::new(), String::new()),
            };
            rows.push(CsvRow {
                claim_number,
                claim_title,
                receipt_ref: String::new(),
                date: e.occurred_at.clone().unwrap_or_default(),
                merchant: e.merchant_name.clone().unwrap_or_default(),
                category: e.category.clone(),
                description: e.description.clone(),
                currency: e.currency.clone().unwrap_or_default(),
                amount_minor: e.total_amount_minor,
                tax_minor: e.tax_amount_minor,
                status: e.status.as_str().to_string(),
                receipt_file: e.receipt_filename.clone().unwrap_or_default(),
                expense_id: e.id.clone(),
            });
        }
        drop(db);
        let file_name = format!("Folio-expenses-{}.csv", &now()[..10]);
        self.write_csv_export(&rows, file_name, None)
    }
    fn write_csv_export(
        &self,
        rows: &[CsvRow],
        file_name: String,
        audit_entity: Option<&str>,
    ) -> Result<CsvExport> {
        let bytes = render(rows);
        let export_id = id();
        let relative = format!("exports/csv/{export_id}.csv");
        let path = self.paths.resolve(&relative)?;
        let temp = self.paths.resolve(&format!("cache/{export_id}.part"))?;
        {
            let mut f = fs::File::create(&temp)?;
            f.write_all(&bytes)?;
            f.sync_all()?;
        }
        if path.exists() {
            fs::remove_file(&path)?;
        }
        fs::rename(&temp, &path)?;
        let mut db = self.conn()?;
        let tx = db.transaction()?;
        repository::audit(
            &tx,
            "csv.exported",
            audit_entity.unwrap_or(&export_id),
            serde_json::json!({"exportId":export_id,"fileName":file_name,"rows":rows.len()}),
        )?;
        tx.commit()?;
        drop(db);
        let settings = self.settings()?;
        let mut exported_file_name = file_name;
        if let Some(folder) = settings.export_directory {
            let dir = std::path::Path::new(&folder);
            let mut written = None;
            for attempt in 1..=MAX_EXPORT_COLLISION_ATTEMPTS {
                let candidate = export_candidate_name(&exported_file_name, attempt);
                let destination = dir.join(&candidate);
                let outcome = (|| -> std::io::Result<()> {
                    let mut file = fs::OpenOptions::new()
                        .write(true)
                        .create_new(true)
                        .open(&destination)?;
                    file.write_all(&bytes)?;
                    file.sync_all()
                })();
                match outcome {
                    Ok(()) => {
                        written = Some(candidate);
                        break;
                    }
                    // Re-exporting after an earlier export already wrote this
                    // name: try the next `(n)` suffix instead of failing.
                    Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => continue,
                    Err(_) => break,
                }
            }
            match written {
                Some(name) => exported_file_name = name,
                None => {
                    return Err(AppError::new("ExportCopyError",format!("The CSV is saved in Folio, but could not be copied to the export directory. Local copy: {}",path.display())));
                }
            }
        }
        Ok(CsvExport {
            id: export_id,
            file_name: exported_file_name,
            path: path.to_string_lossy().to_string(),
            rows: rows.len() as u32,
        })
    }
    pub fn csv_export_path(&self, id: &str) -> Result<String> {
        uuid::Uuid::parse_str(id).map_err(|_| AppError::invalid("Invalid export ID."))?;
        let path = self.paths.resolve(&format!("exports/csv/{id}.csv"))?;
        if !path.exists() {
            return Err(AppError::not_found());
        }
        Ok(path.to_string_lossy().to_string())
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    fn row(
        merchant: &str,
        currency: &str,
        amount: Option<i64>,
        tax: Option<i64>,
        receipt_ref: &str,
    ) -> CsvRow {
        CsvRow {
            claim_number: "CL-1".into(),
            claim_title: "Trip".into(),
            receipt_ref: receipt_ref.into(),
            date: "2026-09-27".into(),
            merchant: merchant.into(),
            category: "Meals".into(),
            description: String::new(),
            currency: currency.into(),
            amount_minor: amount,
            tax_minor: tax,
            status: "ready".into(),
            receipt_file: "receipt.png".into(),
            expense_id: "e1".into(),
        }
    }
    fn text(bytes: &[u8]) -> String {
        String::from_utf8(bytes.to_vec()).unwrap()
    }
    #[test]
    fn output_starts_with_bom_and_uses_crlf() {
        let out = render(&[row("Cafe", "MYR", Some(8450), Some(478), "R001")]);
        assert_eq!(&out[..3], [0xEF, 0xBB, 0xBF]);
        let s = text(&out[3..]);
        assert!(s.contains("\r\n"));
        assert!(!s.replace("\r\n", "").contains('\n'));
        assert_eq!(s.lines().count(), 2);
    }
    #[test]
    fn header_matches_spec_order() {
        let out = render(&[]);
        let s = text(&out[3..]);
        let first_line = s.split("\r\n").next().unwrap();
        assert_eq!(
            first_line,
            "Claim Number,Claim Title,Receipt Ref,Date,Merchant,Category,Description,Currency,Amount,Tax,Status,Receipt File,Expense ID"
        );
    }
    #[test]
    fn commas_quotes_and_newlines_are_quoted_per_rfc4180() {
        let out = render(&[row("Cafe, \"Best\"\nEver", "MYR", Some(100), None, "R001")]);
        let s = text(&out[3..]);
        assert!(s.contains("\"Cafe, \"\"Best\"\"\nEver\""));
    }
    #[test]
    fn formula_injection_prefix_is_applied_except_on_amounts() {
        let out = render(&[row("=SUM(A1:A9)", "MYR", Some(100), None, "R001")]);
        let s = text(&out[3..]);
        assert!(s.contains("'=SUM(A1:A9)"));
        let out = render(&[row("-drop", "MYR", Some(100), None, "R001")]);
        assert!(text(&out[3..]).contains("'-drop"));
        let out = render(&[row("@formula", "MYR", Some(100), None, "R001")]);
        assert!(text(&out[3..]).contains("'@formula"));
        let out = render(&[row("+formula", "MYR", Some(100), None, "R001")]);
        assert!(text(&out[3..]).contains("'+formula"));
    }
    #[test]
    fn amounts_format_by_currency_exponent_with_integer_arithmetic() {
        assert_eq!(format_money(150, 0), "150");
        assert_eq!(format_money(150, 2), "1.50");
        assert_eq!(format_money(12345, 3), "12.345");
        assert_eq!(format_money(5, 3), "0.005");
        let out = render(&[row("JPY shop", "JPY", Some(1500), None, "R001")]);
        assert!(text(&out[3..]).contains(",1500,"));
        let out = render(&[row("BHD shop", "BHD", Some(12345), Some(5), "R001")]);
        let s = text(&out[3..]);
        assert!(s.contains(",12.345,0.005,"));
    }
    #[test]
    fn missing_amount_renders_blank_cell() {
        let out = render(&[row("No total", "MYR", None, None, "")]);
        let s = text(&out[3..]);
        let last = s.split("\r\n").nth(1).unwrap();
        let cells: Vec<&str> = last.split(',').collect();
        assert_eq!(cells[8], "");
        assert_eq!(cells[9], "");
    }
}
