use super::AppService;
use crate::{
    domain::{claim::Claim, expense::currency_exponent, id, now},
    error::{AppError, Result},
    repository::{self, claim_repository as claims, expense_repository as expenses},
};
use rust_xlsxwriter::Workbook;
use serde::{Deserialize, Serialize};
use std::{
    collections::{HashMap, HashSet},
    fs,
    io::Write,
};
use ts_rs::TS;
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CsvExport {
    pub id: String,
    pub file_name: String,
    pub path: String,
    pub rows: u32,
}
const HEADER: [&str; 15] = [
    "Claim Number",
    "Claim Title",
    "Receipt Ref",
    "Date",
    "Merchant",
    "Category",
    "Description",
    "Currency",
    "Amount",
    "Tax",
    "Status",
    "Receipt File",
    "Expense ID",
    "Personal Name",
    "Organization",
];
struct CsvRow {
    claim_number: String,
    claim_title: String,
    receipt_ref: String,
    date: String,
    merchant: String,
    category: String,
    description: String,
    currency: String,
    amount_minor: Option<i64>,
    tax_minor: Option<i64>,
    status: String,
    receipt_file: String,
    expense_id: String,
    personal_name: String,
    organization: String,
}
/// Prefixes a cell with `'` when it starts with a character a spreadsheet would
/// treat as the start of a formula, per the CSV export's formula-injection guard.
fn guard_formula(value: &str) -> String {
    if value.starts_with(['=', '+', '-', '@', '\t', '\r']) {
        format!("'{value}")
    } else {
        value.to_string()
    }
}
/// Quotes a field per RFC 4180 when it contains a comma, quote, or newline,
/// doubling any embedded quotes.
fn quote(value: &str) -> String {
    if value.contains([',', '"', '\n', '\r']) {
        format!("\"{}\"", value.replace('"', "\"\""))
    } else {
        value.to_string()
    }
}
/// A text cell: formula-guarded, then RFC 4180 quoted.
fn text_cell(value: &str) -> String {
    quote(&guard_formula(value))
}
/// Formats minor units as a plain decimal using integer arithmetic only, per
/// the currency's exponent (e.g. JPY -> "150", BHD -> "12.345").
fn format_money(minor: i64, exponent: u32) -> String {
    if exponent == 0 {
        return minor.to_string();
    }
    let factor = 10_i64.pow(exponent);
    format!(
        "{}.{:0width$}",
        minor / factor,
        minor % factor,
        width = exponent as usize
    )
}
/// The Amount/Tax cells are numeric values generated by the app, so they are
/// never formula-guarded or quoted (Global Constraints CSV rules).
fn money_cell(minor: Option<i64>, currency: &str) -> String {
    match minor {
        None => String::new(),
        Some(m) => format_money(m, currency_exponent(currency).unwrap_or(2)),
    }
}
/// The maximum number of collision-avoidance attempts tried against the
/// export directory: the base name, then ` (2)` through ` (999)`.
const MAX_EXPORT_COLLISION_ATTEMPTS: u32 = 999;
/// Builds the `n`th candidate file name for the export directory: `n == 1`
/// is the base human file name, `n >= 2` inserts ` (n)` before `.csv`.
fn export_candidate_name(file_name: &str, n: u32) -> String {
    if n <= 1 {
        return file_name.to_string();
    }
    match file_name.rfind('.') {
        Some(dot) => format!("{} ({n}){}", &file_name[..dot], &file_name[dot..]),
        None => format!("{file_name} ({n})"),
    }
}
fn render(rows: &[CsvRow]) -> Vec<u8> {
    let mut out = vec![0xEF, 0xBB, 0xBF];
    let header = HEADER
        .iter()
        .map(|h| text_cell(h))
        .collect::<Vec<_>>()
        .join(",");
    out.extend_from_slice(header.as_bytes());
    out.extend_from_slice(b"\r\n");
    for r in rows {
        let cells = [
            text_cell(&r.claim_number),
            text_cell(&r.claim_title),
            text_cell(&r.receipt_ref),
            text_cell(&r.date),
            text_cell(&r.merchant),
            text_cell(&r.category),
            text_cell(&r.description),
            text_cell(&r.currency),
            money_cell(r.amount_minor, &r.currency),
            money_cell(r.tax_minor, &r.currency),
            text_cell(&r.status),
            text_cell(&r.receipt_file),
            text_cell(&r.expense_id),
            text_cell(&r.personal_name),
            text_cell(&r.organization),
        ];
        out.extend_from_slice(cells.join(",").as_bytes());
        out.extend_from_slice(b"\r\n");
    }
    out
}
fn render_xlsx(rows: &[CsvRow]) -> Result<Vec<u8>> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();
    worksheet
        .set_name("Expenses")
        .map_err(|_| AppError::new("ExportError", "Unable to create the Excel workbook."))?;
    for (col, header) in HEADER.iter().enumerate() {
        worksheet
            .write_string(0, col as u16, *header)
            .map_err(|_| AppError::new("ExportError", "Unable to create the Excel workbook."))?;
    }
    for (idx, r) in rows.iter().enumerate() {
        let row = (idx + 1) as u32;
        let currency = &r.currency;
        let cells = [
            r.claim_number.as_str(),
            r.claim_title.as_str(),
            r.receipt_ref.as_str(),
            r.date.as_str(),
            r.merchant.as_str(),
            r.category.as_str(),
            r.description.as_str(),
            currency.as_str(),
            "",
            "",
            r.status.as_str(),
            r.receipt_file.as_str(),
            r.expense_id.as_str(),
            r.personal_name.as_str(),
            r.organization.as_str(),
        ];
        for (col, value) in cells.iter().enumerate() {
            if col == 8 || col == 9 {
                continue;
            }
            worksheet
                .write_string(row, col as u16, *value)
                .map_err(|_| {
                    AppError::new("ExportError", "Unable to create the Excel workbook.")
                })?;
        }
        if let Some(amount) = r.amount_minor {
            worksheet
                .write_number(row, 8, money_number(amount, currency))
                .map_err(|_| {
                    AppError::new("ExportError", "Unable to create the Excel workbook.")
                })?;
        }
        if let Some(tax) = r.tax_minor {
            worksheet
                .write_number(row, 9, money_number(tax, currency))
                .map_err(|_| {
                    AppError::new("ExportError", "Unable to create the Excel workbook.")
                })?;
        }
    }
    worksheet.autofit();
    workbook
        .save_to_buffer()
        .map_err(|_| AppError::new("ExportError", "Unable to create the Excel workbook."))
}
fn money_number(minor: i64, currency: &str) -> f64 {
    let exponent = currency_exponent(currency).unwrap_or(2);
    if exponent == 0 {
        minor as f64
    } else {
        minor as f64 / 10_i64.pow(exponent) as f64
    }
}
/// Where and how each tabular export format is stored.
struct TabularFormat {
    dir: &'static str,
    ext: &'static str,
    audit_action: &'static str,
    label: &'static str,
}
impl TabularFormat {
    const CSV: Self = Self {
        dir: "exports/csv",
        ext: "csv",
        audit_action: "csv.exported",
        label: "CSV",
    };
    const XLSX: Self = Self {
        dir: "exports/xlsx",
        ext: "xlsx",
        audit_action: "xlsx.exported",
        label: "Excel file",
    };
}
impl AppService {
    /// Personal name and optional organization from Settings, stamped on every
    /// exported row so a spreadsheet stands on its own for personal or
    /// organizational use. Read before any DB lock is taken.
    fn export_identity(&self) -> Result<(String, String)> {
        let settings = self.settings()?;
        Ok((
            settings.employee.trim().to_string(),
            settings.company.trim().to_string(),
        ))
    }
    fn claim_rows(&self, claim_id: &str) -> Result<(Claim, Vec<CsvRow>)> {
        let (personal_name, organization) = self.export_identity()?;
        let db = self.conn()?;
        let claim = claims::get(&db, claim_id)?;
        let members: Vec<_> = expenses::all(&db)?
            .into_iter()
            .filter(|e| e.claim_id.as_deref() == Some(claim_id))
            .collect();
        drop(db);
        let rows = members
            .iter()
            .enumerate()
            .map(|(index, e)| CsvRow {
                claim_number: claim.claim_number.clone(),
                claim_title: claim.title.clone(),
                receipt_ref: e
                    .receipt_id
                    .as_ref()
                    .map(|_| format!("R{:03}", index + 1))
                    .unwrap_or_default(),
                date: e.occurred_at.clone().unwrap_or_default(),
                merchant: e.merchant_name.clone().unwrap_or_default(),
                category: e.category.clone(),
                description: e.description.clone(),
                currency: e.currency.clone().unwrap_or_else(|| claim.currency.clone()),
                amount_minor: e.total_amount_minor,
                tax_minor: e.tax_amount_minor,
                status: e.status.as_str().to_string(),
                receipt_file: e.receipt_filename.clone().unwrap_or_default(),
                expense_id: e.id.clone(),
                personal_name: personal_name.clone(),
                organization: organization.clone(),
            })
            .collect();
        Ok((claim, rows))
    }
    fn selected_expense_rows(&self, expense_ids: Vec<String>) -> Result<Vec<CsvRow>> {
        if expense_ids.is_empty() || expense_ids.len() > 5000 {
            return Err(AppError::invalid("Select 1 to 5000 expenses to export."));
        }
        let mut seen = HashSet::new();
        let mut unique = Vec::with_capacity(expense_ids.len());
        for raw in &expense_ids {
            uuid::Uuid::parse_str(raw).map_err(|_| AppError::invalid("Invalid expense ID."))?;
            if seen.insert(raw.clone()) {
                unique.push(raw.clone());
            }
        }
        let (personal_name, organization) = self.export_identity()?;
        let db = self.conn()?;
        let mut claim_cache: HashMap<String, Claim> = HashMap::new();
        let mut rows = Vec::with_capacity(unique.len());
        for eid in &unique {
            let e = expenses::get(&db, eid)?;
            let (claim_number, claim_title) = match e.claim_id {
                Some(ref cid) => {
                    if !claim_cache.contains_key(cid) {
                        let c = claims::get(&db, cid)?;
                        claim_cache.insert(cid.clone(), c);
                    }
                    let c = &claim_cache[cid];
                    (c.claim_number.clone(), c.title.clone())
                }
                None => (String::new(), String::new()),
            };
            rows.push(CsvRow {
                claim_number,
                claim_title,
                receipt_ref: String::new(),
                date: e.occurred_at.clone().unwrap_or_default(),
                merchant: e.merchant_name.clone().unwrap_or_default(),
                category: e.category.clone(),
                description: e.description.clone(),
                currency: e.currency.clone().unwrap_or_default(),
                amount_minor: e.total_amount_minor,
                tax_minor: e.tax_amount_minor,
                status: e.status.as_str().to_string(),
                receipt_file: e.receipt_filename.clone().unwrap_or_default(),
                expense_id: e.id.clone(),
                personal_name: personal_name.clone(),
                organization: organization.clone(),
            });
        }
        Ok(rows)
    }
    pub fn export_claim_csv(&self, claim_id: &str) -> Result<CsvExport> {
        let (claim, rows) = self.claim_rows(claim_id)?;
        let file_name = format!("Folio-{}.csv", claim.claim_number);
        self.write_csv_export(&rows, file_name, Some(claim_id))
    }
    pub fn export_expenses_csv(&self, expense_ids: Vec<String>) -> Result<CsvExport> {
        let rows = self.selected_expense_rows(expense_ids)?;
        let file_name = format!("Folio-expenses-{}.csv", &now()[..10]);
        self.write_csv_export(&rows, file_name, None)
    }
    pub fn export_claim_xlsx(&self, claim_id: &str) -> Result<CsvExport> {
        let (claim, rows) = self.claim_rows(claim_id)?;
        let file_name = format!("Folio-{}.xlsx", claim.claim_number);
        self.write_xlsx_export(&rows, file_name, Some(claim_id))
    }
    pub fn export_expenses_xlsx(&self, expense_ids: Vec<String>) -> Result<CsvExport> {
        let rows = self.selected_expense_rows(expense_ids)?;
        let file_name = format!("Folio-expenses-{}.xlsx", &now()[..10]);
        self.write_xlsx_export(&rows, file_name, None)
    }
    fn write_csv_export(
        &self,
        rows: &[CsvRow],
        file_name: String,
        audit_entity: Option<&str>,
    ) -> Result<CsvExport> {
        self.write_tabular_export(
            &TabularFormat::CSV,
            render(rows),
            rows.len(),
            file_name,
            audit_entity,
        )
    }
    fn write_xlsx_export(
        &self,
        rows: &[CsvRow],
        file_name: String,
        audit_entity: Option<&str>,
    ) -> Result<CsvExport> {
        self.write_tabular_export(
            &TabularFormat::XLSX,
            render_xlsx(rows)?,
            rows.len(),
            file_name,
            audit_entity,
        )
    }
    /// Stores an export inside Folio's data directory (atomic temp + rename),
    /// records an audit entry, then copies it to the user's export directory
    /// with ` (n)` collision naming. Shared by CSV and Excel so their
    /// storage, audit and copy behaviour cannot drift apart.
    fn write_tabular_export(
        &self,
        format: &TabularFormat,
        bytes: Vec<u8>,
        row_count: usize,
        file_name: String,
        audit_entity: Option<&str>,
    ) -> Result<CsvExport> {
        let export_id = id();
        let path = self
            .paths
            .resolve(&format!("{}/{export_id}.{}", format.dir, format.ext))?;
        let temp = self.paths.resolve(&format!("cache/{export_id}.part"))?;
        {
            let mut f = fs::File::create(&temp)?;
            f.write_all(&bytes)?;
            f.sync_all()?;
        }
        if path.exists() {
            fs::remove_file(&path)?;
        }
        fs::rename(&temp, &path)?;
        let mut db = self.conn()?;
        let tx = db.transaction()?;
        repository::audit(
            &tx,
            format.audit_action,
            audit_entity.unwrap_or(&export_id),
            serde_json::json!({"exportId":export_id,"fileName":file_name,"rows":row_count}),
        )?;
        tx.commit()?;
        drop(db);
        let settings = self.settings()?;
        let mut exported_file_name = file_name;
        if let Some(folder) = settings.export_directory {
            let dir = std::path::Path::new(&folder);
            let mut written = None;
            for attempt in 1..=MAX_EXPORT_COLLISION_ATTEMPTS {
                let candidate = export_candidate_name(&exported_file_name, attempt);
                let destination = dir.join(&candidate);
                let outcome = (|| -> std::io::Result<()> {
                    let mut file = fs::OpenOptions::new()
                        .write(true)
                        .create_new(true)
                        .open(&destination)?;
                    file.write_all(&bytes)?;
                    file.sync_all()
                })();
                match outcome {
                    Ok(()) => {
                        written = Some(candidate);
                        break;
                    }
                    // Re-exporting after an earlier export already wrote this
                    // name: try the next `(n)` suffix instead of failing.
                    Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => continue,
                    Err(_) => break,
                }
            }
            match written {
                Some(name) => exported_file_name = name,
                None => {
                    return Err(AppError::new(
                        "ExportCopyError",
                        format!(
                            "The {} is saved in Folio, but could not be copied to the export directory. Local copy: {}",
                            format.label,
                            path.display()
                        ),
                    ));
                }
            }
        }
        Ok(CsvExport {
            id: export_id,
            file_name: exported_file_name,
            path: path.to_string_lossy().to_string(),
            rows: row_count as u32,
        })
    }
    fn tabular_export_path(&self, format: &TabularFormat, id: &str) -> Result<String> {
        uuid::Uuid::parse_str(id).map_err(|_| AppError::invalid("Invalid export ID."))?;
        let path = self
            .paths
            .resolve(&format!("{}/{id}.{}", format.dir, format.ext))?;
        if !path.exists() {
            return Err(AppError::not_found());
        }
        Ok(path.to_string_lossy().to_string())
    }
    pub fn csv_export_path(&self, id: &str) -> Result<String> {
        self.tabular_export_path(&TabularFormat::CSV, id)
    }
    pub fn xlsx_export_path(&self, id: &str) -> Result<String> {
        self.tabular_export_path(&TabularFormat::XLSX, id)
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    fn row(
        merchant: &str,
        currency: &str,
        amount: Option<i64>,
        tax: Option<i64>,
        receipt_ref: &str,
    ) -> CsvRow {
        CsvRow {
            claim_number: "CL-1".into(),
            claim_title: "Trip".into(),
            receipt_ref: receipt_ref.into(),
            date: "2026-09-27".into(),
            merchant: merchant.into(),
            category: "Meals".into(),
            description: String::new(),
            currency: currency.into(),
            amount_minor: amount,
            tax_minor: tax,
            status: "ready".into(),
            receipt_file: "receipt.png".into(),
            expense_id: "e1".into(),
            personal_name: String::new(),
            organization: String::new(),
        }
    }
    fn text(bytes: &[u8]) -> String {
        String::from_utf8(bytes.to_vec()).unwrap()
    }
    #[test]
    fn output_starts_with_bom_and_uses_crlf() {
        let out = render(&[row("Cafe", "MYR", Some(8450), Some(478), "R001")]);
        assert_eq!(&out[..3], [0xEF, 0xBB, 0xBF]);
        let s = text(&out[3..]);
        assert!(s.contains("\r\n"));
        assert!(!s.replace("\r\n", "").contains('\n'));
        assert_eq!(s.lines().count(), 2);
    }
    #[test]
    fn header_matches_spec_order() {
        let out = render(&[]);
        let s = text(&out[3..]);
        let first_line = s.split("\r\n").next().unwrap();
        assert_eq!(
            first_line,
            "Claim Number,Claim Title,Receipt Ref,Date,Merchant,Category,Description,Currency,Amount,Tax,Status,Receipt File,Expense ID,Personal Name,Organization"
        );
    }
    #[test]
    fn personal_name_and_optional_organization_are_exported() {
        let mut r = row("Cafe", "MYR", Some(100), None, "R001");
        r.personal_name = "Nurhan".into();
        let out = render(&[r]);
        let s = text(&out[3..]);
        let data = s.split("\r\n").nth(1).unwrap();
        assert!(data.ends_with(",Nurhan,"), "row was: {data}");
    }
    #[test]
    fn commas_quotes_and_newlines_are_quoted_per_rfc4180() {
        let out = render(&[row("Cafe, \"Best\"\nEver", "MYR", Some(100), None, "R001")]);
        let s = text(&out[3..]);
        assert!(s.contains("\"Cafe, \"\"Best\"\"\nEver\""));
    }
    #[test]
    fn formula_injection_prefix_is_applied_except_on_amounts() {
        let out = render(&[row("=SUM(A1:A9)", "MYR", Some(100), None, "R001")]);
        let s = text(&out[3..]);
        assert!(s.contains("'=SUM(A1:A9)"));
        let out = render(&[row("-drop", "MYR", Some(100), None, "R001")]);
        assert!(text(&out[3..]).contains("'-drop"));
        let out = render(&[row("@formula", "MYR", Some(100), None, "R001")]);
        assert!(text(&out[3..]).contains("'@formula"));
        let out = render(&[row("+formula", "MYR", Some(100), None, "R001")]);
        assert!(text(&out[3..]).contains("'+formula"));
    }
    #[test]
    fn amounts_format_by_currency_exponent_with_integer_arithmetic() {
        assert_eq!(format_money(150, 0), "150");
        assert_eq!(format_money(150, 2), "1.50");
        assert_eq!(format_money(12345, 3), "12.345");
        assert_eq!(format_money(5, 3), "0.005");
        let out = render(&[row("JPY shop", "JPY", Some(1500), None, "R001")]);
        assert!(text(&out[3..]).contains(",1500,"));
        let out = render(&[row("BHD shop", "BHD", Some(12345), Some(5), "R001")]);
        let s = text(&out[3..]);
        assert!(s.contains(",12.345,0.005,"));
    }
    #[test]
    fn xlsx_render_creates_zip_workbook_with_rows() {
        let out = render_xlsx(&[row("Cafe", "MYR", Some(8450), Some(478), "R001")]).unwrap();
        assert!(out.starts_with(b"PK"));
        assert!(out.len() > 1000);
    }
    fn xlsx_part(bytes: &[u8], name: &str) -> String {
        use std::io::Read;
        let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
        let mut part = archive.by_name(name).unwrap();
        let mut xml = String::new();
        part.read_to_string(&mut xml).unwrap();
        xml
    }
    #[test]
    fn xlsx_stores_formula_like_text_as_strings_not_formulas() {
        let hostile = [
            "=SUM(A1:A9)",
            "+cmd|' /C calc'!A0",
            "-2+3",
            "@HYPERLINK(\"x\")",
        ];
        let rows: Vec<CsvRow> = hostile
            .iter()
            .map(|m| {
                let mut r = row(m, "MYR", Some(100), None, "R001");
                r.description = (*m).to_string();
                r
            })
            .collect();
        let out = render_xlsx(&rows).unwrap();
        let sheet = xlsx_part(&out, "xl/worksheets/sheet1.xml");
        assert!(
            !sheet.contains("<f>"),
            "worksheet must contain no formula cells"
        );
        assert!(
            !sheet.contains("<f "),
            "worksheet must contain no formula cells"
        );
        let strings = xlsx_part(&out, "xl/sharedStrings.xml");
        for h in ["=SUM(A1:A9)", "-2+3"] {
            assert!(strings.contains(h), "{h} should be stored verbatim as text");
        }
    }
    #[test]
    fn xlsx_amounts_are_numeric_cells_scaled_by_currency_exponent() {
        let out = render_xlsx(&[
            row("Cafe", "MYR", Some(8450), None, "R001"),
            row("Shop", "JPY", Some(1500), None, "R002"),
            row("Souq", "BHD", Some(12345), None, "R003"),
        ])
        .unwrap();
        let sheet = xlsx_part(&out, "xl/worksheets/sheet1.xml");
        assert!(sheet.contains("<c r=\"I2\"><v>84.5</v></c>"), "{sheet}");
        assert!(sheet.contains("<c r=\"I3\"><v>1500</v></c>"));
        assert!(sheet.contains("<c r=\"I4\"><v>12.345</v></c>"));
    }
    #[test]
    fn missing_amount_renders_blank_cell() {
        let out = render(&[row("No total", "MYR", None, None, "")]);
        let s = text(&out[3..]);
        let last = s.split("\r\n").nth(1).unwrap();
        let cells: Vec<&str> = last.split(',').collect();
        assert_eq!(cells[8], "");
        assert_eq!(cells[9], "");
    }
}
